### ISSUE TITLE
Move `BDL` to `Bot` class

### ISSUE THREAD

**Issue by SirThane** [SUPERMECHM500/MWSRam#22]
On better inspection, connecting DBL on each cog that requires it is unnecessary. All connections are the same. Move to an attribute of `Bot`. Add `Bot` method for connecting, and for `DBLClient.get_user_vote` that includes connectivity checking that will return `False` if not connected and warn of connection status.

**Comment by SirThane** [comment]
One instance of `dblpy` uses a kwarg `autopost=True`. Need to determine the usage of this and if it can be done without setting it at the DBLClient instantiation. Can it be overridden in the `DBLClient.get_user_vote` method? If so, safe to move to `Bot`.

**Comment by IlexisTheMadcat** [comment]
Auto-post updates the guild count of the bot to the website every thirty minutes, and is initialized on the creation of DBLClient via `DBLClient(token, auto_post=bool())`.

That said, there should be no need to override it.

**Comment by SirThane** [comment]
Completed in linked merges.
