### ISSUE TITLE
Add check to `get_user_vote` for active DBLClient connection

### ISSUE THREAD

**Issue by SirThane** [SUPERMECHM500/MWSRam#30]
If DBL is not connected, it will return False when checked. Add check and optional message to `ctx.author` if DBL is not connected.

**Comment by SirThane** [comment]
Idea:
`Bot.get_user_vote` to return:
* `True` if owner or user voted
* `False` if user not voted
* `None` if DBL not connected

This will allow capturing connection state and change output of command

**Comment by IlexisTheMadcat** [comment]
```
if bot.get_user_vote(ctx.author.id) is None:
    pass  # just let the command run
```

**Comment by SirThane** [comment]
If you're going to do that, do it in the callback, not each and every time it's used. Change `bot.get_user_vote` to return `True` instead of `None` `if not self.dbl`.

**Comment by IlexisTheMadcat** [comment]
Gonna close this since we have no problem with it.
