### ISSUE TITLE
Create `[p]tail` command

### ISSUE THREAD

**Issue by SirThane** [SUPERMECHM500/MWSRam#33]
Add a command to tail the pm2 logs per bot.
Suggest sending in a `diff` markdown box so that stdout can be displayed in green and `stderr` can be displayed in red, mimicking the `pm2 logs` command. 

Can use `tail -{int: number of lines} {str: log file name}` in `os.popen()` to get the last X lines.

Logs are located at `~/.pm2/{app name}-out.log` and `~/.pm2/{app name}-err.log`.

**Comment by SirThane** [comment]
A better solution may be to use `tail` from `sh`. Must install from `pip`. 
https://stackoverflow.com/questions/12523044/how-can-i-tail-a-log-file-in-python

**Comment by IlexisTheMadcat** [comment]
Has this been resolved yet? It appears we have a working tail command.

**Comment by SirThane** [comment]
I want to change it to use plain messages instead of embeds and to either truncate or paginate it if it's over 2000 characters. Just haven't had the chance to be back on it.
