### ISSUE TITLE
Idea: `Bot.cprint()` method

### ISSUE THREAD

**Issue by SirThane** [SUPERMECHM500/MWSRam#34]
Create new method for `Bot` that accepts 2 parameters and prints to console. This will help to align all content that is printed to console.

e.g.
```python
from datetime import datetime

def cprint(self, tag: str, content: str) -> None:
    ts = datetime.utcnow().strftime("%Y/%m/%d %H:%M:%S")
    print(f"[{ts} || {tag.upper()}] {content}")
```

Then have all `print`s forward be calls to

**Comment by IlexisTheMadcat** [comment]
I had this in my thing of random scripts
Install `termcolor` using pip.
```python
def print(*objects, color=None, highlight=None, attrs=None, sep=' ', end='\n', file=sys.stdout, flush=False):
    termcolor.cprint(*objects, color, highlight, attrs, sep, end, file, flush)
```

**Comment by SirThane** [comment]
Things like `colorama` and `termcolor` won't help much with the bots anymore. My thought was more towards forcing a certain formatting of the messages printed to console. Typically, something like this is done with the `logging` std lib, but `pm2`'s logs server this purpose well enough.
